plats = [
    {"name": "Eru".upper(), "image": "plats/food/eru3.jpg", "price": 1500, "prod_type": "food", "stock": 0},
    {"name": "Koki".upper(), "image": "plats/food/koki.jpg", "price": 3000, "prod_type": "food", "stock": 0},
    {"name": "Ndole".upper(), "image": "plats/food/ndole2.jpg", "price": 2500, "prod_type": "food", "stock": 0},
    {"name": "Ndole viande".upper(), "image": "plats/food/ndole3.jpg", "price": 2500, "prod_type": "food", "stock": 0},
    {"name": "Okok ewondo".upper(), "image": "plats/food/okok.jpg", "price": 1500, "prod_type": "food", "stock": 0},
    {"name": "Okok eton".upper(), "image": "plats/food/okok2.jpg", "price": 1500, "prod_type": "food", "stock": 0},
    {"name": "Okok bulu".upper(), "image": "plats/food/okok3.jpg", "price": 1500, "prod_type": "food", "stock": 0},
    {"name": "Okok bassa".upper(), "image": "plats/food/okok4.jpg", "price": 1500, "prod_type": "food", "stock": 0},
    {"name": "Poisson braisé".upper(), "image": "plats/food/pb.jpg", "price": 3500, "prod_type": "food", "stock": 0},
    {"name": "Poulet DG".upper(), "image": "plats/food/pdg.jpg", "price": 2000, "prod_type": "food", "stock": 0},
    {"name": "Taro".upper(), "image": "plats/food/taro.jpg", "price": 2500, "prod_type": "food", "stock": 0},
    {"name": "Champagne".upper(), "image": "plats/vins/champagne.jpg", "price": 45000, "prod_type": "drink", "stock": 5},
    {"name": "Baileys".upper(), "image": "plats/vins/whisky.png", "price": 9000, "prod_type": "drink", "stock": 3},
    {"name": "Amarula".upper(), "image": "plats/vins/whisky.png", "price": 8000, "prod_type": "drink", "stock": 2},
    {"name": "Campari".upper(), "image": "plats/vins/whisky.png", "price": 15000, "prod_type": "drink", "stock": 4},
    {"name": "Jack Daniels".upper(), "image": "plats/vins/whisky.png", "price": 18500, "prod_type": "drink", "stock": 10},
    {"name": "Pastis".upper(), "image": "plats/vins/whisky.png", "price": 50000, "prod_type": "drink", "stock": 6},
    {"name": "Henri pinot".upper(), "image": "plats/vins/vins (1).jpg", "price": 25000, "prod_type": "drink", "stock": 10},
    {"name": "cabernet sauvignon".upper(), "image": "plats/vins/vins (2).jpg", "price": 35000, "prod_type": "drink", "stock": 3},
    {"name": "malbec".upper(), "image": "plats/vins/vins (3).jpg", "price": 15000, "prod_type": "drink", "stock": 15},
    {"name": "merlot".upper(), "image": "plats/vins/vins (4).jpg", "price": 20000, "prod_type": "drink", "stock": 7},
    {"name": "pinot noir".upper(), "image": "plats/vins/vins (5).jpg", "price": 30000, "prod_type": "drink", "stock": 5},
    {"name": "chardonnay".upper(), "image": "plats/vins/vins (6).jpg", "price": 20000, "prod_type": "drink", "stock": 4},
    {"name": "syrah".upper(), "image": "plats/vins/vins (7).jpg", "price": 18000, "prod_type": "drink", "stock": 2},
    {"name": "kuelin alsace".upper(), "image": "plats/vins/vins (8).jpg", "price": 22000, "prod_type": "drink", "stock": 1},
    {"name": "sauvignon blanc".upper(), "image": "plats/vins/vins (9).jpg", "price": 33000, "prod_type": "drink", "stock": 1},
    {"name": "lutz".upper(), "image": "plats/vins/vins (10).jpg", "price": 42000, "prod_type": "drink", "stock": 6},
    {"name": "chenin blanc".upper(), "image": "plats/vins/vins (11).jpg", "price": 26000, "prod_type": "drink", "stock": 3},
]

